apps/casino/urls.py
"""
Casino Apps URLs
"""
from django.urls import path

from . import views

app_name = "casino"

urlpatterns = [
    path("home", views.IndexView.as_view(), name="home"),
    path("start", views.GameView.as_view(), name="start")
]

apps/home/urls.py
"""
Casino Apps URLs
"""
from django.urls import path

from . import views

app_name = "home"

urlpatterns = [
    path('', views.IndexView.as_view()),
    path('add-new-application', views.AddView.as_view(), name="add"),
]

groupe6/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("casino/", include("apps.casino.urls")),
    path("", include("apps.home.urls")),
]

apps/casino/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _


class Account(models.Model):
    """Account's model"""

    # username, email, password, {first,last}name are provided by contrib.auth.models.User model
    user = models.OneToOneField(
        to=User, on_delete=models.CASCADE, verbose_name=_("User")
    )
    solde = models.IntegerField(
        default=0,
    )

apps/home/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class Application(models.Model):
    nom = models.CharField(
        unique=True,
        error_messages={
            'unique': _("An application with that name already exists."),
        },
        max_length=128,
    )
    active = models.BooleanField(
        default=False,
        help_text=_(
            'Avoid any errors before the apps has been ready'
        ),
    )

apps/home/forms.py
from .models import Application
from django import forms

class ApplicationForm(forms.ModelForm):

    class Meta:
        model = Application
        fields = ["nom", "active"]

apps/casino/views.py
from django.views.generic.base import TemplateView


class IndexView(TemplateView):
    template_name = "casino/index.html"


class GameView(TemplateView):
    template_name = "casino/start.html"

apps/home/views.py
from django.core.management import call_command
from django.views.generic.base import TemplateView
from django.views.generic.edit import FormView

from .forms import ApplicationForm
from .models import Application


class IndexView(TemplateView):
    template_name = "home/index.html"

    def get_object(self, queryset=None):
        return get_object_or_404(Application, pk=self.kwargs["pk"])


class AddView(FormView):
    template_name = "home/add-form.html"
    form_class = ApplicationForm
    success_url = "//"

    def form_valid(self, form):
        call_command('startapp', form.nom)

        return super().form_valid(form)

apps/casino/templates/casino/index.html
{% extends 'base.html' %}

{% block content %}
<h2>Casino Apps</h2>

<h3>Bienvenue à vous</h3>
<p>Vous êtes sur le point de commencer une partie de casino, souhaitez-vous continuer ? <a href="{% url 'casino:start' %}">oui</a></p>
{% {% endblock %} %}

apps/casino/templates/casino/start.html
{% extends 'base.html' %}

{% block content %}
<h3>Quel magnifique choix avez-vous fait !</h3>
<p>Commencons..</p>

<p>Je viens de penser à un nombre entre 1 et 10. Devinez lequel ?
	Att : vous avez le droit à trois essais !
	Si vous devinez mon nombre dès le premier coup, vous gagnez le double de votre mise !
	Si vous le devinez au 2è coup, vous gagnez exactement votre mise !
	Si vous le devinez au 3è coup, vous gagnez la moitiè votre mise !
	Si vous ne le devinez pas au 3è coup, vous perdez votre mise et
	vous avez le droit : 
	de retenter votre chance avec l'argent qu'il vous reste pour reconquérir le level perdu.
	de quitter le jeu.
	Dès que vous devinez mon nombre : vous avez le droit de quitter le jeu et de partir avec vos gains OU de continuer le jeu en passant au level supérieur.</p>
<form action="casino.py" method="post">
	
</form>

{% endblock %}

apps/home/templates/home/add-form.html
{% extends 'base.html' %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Create">
</form>
{% endblock %}

apps/home/templates/home/index.html
{% extends 'base.html' %}

{% block content %}
<h3>dossier générique du groupe 6</h3>
<div>
    <a style="margin-right: 2%;" href="{% url 'casino:home' %}">Casino</a><a href="https://github.com/NavjotSingh0398/casino">github associé</a>
</div>
<div>
    <a href="{% url 'home:add' %}">Ajouter une nouvelle application ?</a>
</div>
{% endblock %}

groupe6/templates/base.html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <!-- Font Awesome -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css">
        <title>Casino</title>
    </head>
    <body>
        <div class="container">
            {% block content %}{% endblock %}
        </div>
        <!-- Optional JavaScript/Css -->
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static '<nom de ton fichier>' %}">
        <script type="text/javascript" src="{% static "<nom de ton fichier>"%}"></script>
        <!-- jQuery first, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>